### ISSUE TITLE
SIGALRM error

### ISSUE THREAD

**Issue by tjturnage** [allenea/Forecast_Search_Wizard#3]
This is the same problem I ran into previously. I'm running Windows 11 and the RUN_ME config files are attached.

Traceback (most recent call last):
  File "C:\data\scripts\Forecast_Search_Wizard-1\RUN_ME\FSW_NAMELIST.py", line 157, in <module>
    main()
  File "C:\data\scripts\Forecast_Search_Wizard-1\RUN_ME\FSW_NAMELIST.py", line 152, in main
    execute(FSW_SEARCH)
  File "C:\data\scripts\Forecast_Search_Wizard-1\src\driver.py", line 53, in execute
    signal.signal(signal.SIGALRM, timeout_handler)
AttributeError: module 'signal' has no attribute 'SIGALRM
[RUN_ME.zip](https://github.com/allenea/Forecast_Search_Wizard/files/8367364/RUN_ME.zip)
'

**Comment by allenea** [comment]
This sounds like a problem that has to do with Anaconda, if we can add anaconda support... great
